#!/bin/bash
# Bash Menu Script Installasion Depedency and fish shell

PS3='Please enter your choice: '
options=("Install Depedency [ Void Linux ]" "Install Depedency [ Artix Linux ]" "Swicth Shell [ All GNU-Linux ]" "Remove Unused File" )
select opt in "${options[@]}"
do
    case $opt in
        "Install Depedency [ Void Linux ]")
            sudo xbps-install -Su xorg xorg-server bspwm sxhkd ncmpcpp feh cava mpd mpc \
            fish-shell xsettingsd dunst mpv neofetch neovim Thunar rofi viewnior xfce4-power-manager \
            pcmanfm tint2 ranger fontconfig rsync wget curl w3m w3m-img ImageMagick pamixer pavucontrol polkit xfce-polkit
            echo "--------------------------"
            echo "install depedency finished"
            echo "--------------------------"
            ;;
        "Install Depedency [ Artix Linux ]")
            sudo pacman -S xorg xorg-server bspwm sxhkd ncmpcpp feh cava mpd mpc \
            fish xsettingsd dunst mpv neofetch neovim thunar rofi viewnior xfce4-power-manager \
            pcmanfm tint2 ranger fontconfig rsync wget curl w3m w3m-img imagemagick pamixer pavucontrol polkit xfce-polkit
            echo "--------------------------"
            echo "install depedency finished"
            echo "--------------------------"
            ;;
        "Swicth Shell [ All GNU-Linux ]")
            chsh -s /usr/bin/fish
            echo "--------------------------"
            echo "swicth shell fish finished"
            echo "--------------------------"
            ;;
        "Remove Unused File")
            rm -rf ${HOME}/preinstalled && rm -rf ${HOME}/readme.md
            echo "--------------------------"
            echo "remove unused file finished"
            echo "--------------------------"
            ;;
        *) echo "Invalid Selection $REPLY";;
    esac
  break
done
