#!/bin/bash
# Bash Menu Script Installasion Depedency and fish shell

# Banner
echo -e ""
echo -e "         dBBBBb  dBBBBP dBBBBBBP dBBBBb dBBBBBb     dBP dBP dBBBBBb
            dB' dBP.BP    dBp       dBP      BB    d8P.dBP       BB
       dBP dB' dBP.BP    dBP    dBBBK'   dBP BB   dBBBBP     dBP BB
      dBP dB' dBP.BP    dBP    dB' db   dBP  BB  dBP BB     dBP  BB
     dBBBBB' dBBBBP    dBP    dBBBBP'  dBBBBBBB dBP dBP    dBBBBBBB"
echo -e ""
echo -e "      Script For Installasion Depedency And Some Stuff C @vcyzteen"
echo -e ""

PS3='Please enter your choice:'
options=("Install Depedency [ Void Linux ]" "Install Depedency [ Artix Linux ]" "Swicth Shell [ All GNU-Linux ]" "Set Chosser File Use Gtk [ Telegram Desktop ]" "Remove Unused File" )
select opt in "${options[@]}"
do
    case $opt in
        "Install Depedency [ Void Linux ]")
            sudo xbps-install -Su xorg xorg-server bspwm sxhkd ncmpcpp feh cava mpd mpc \
            fish-shell xsettingsd dunst mpv neofetch neovim Thunar rofi viewnior xfce4-power-manager \
            pcmanfm tint2 ranger fontconfig rsync wget curl w3m w3m-img ImageMagick pamixer pavucontrol \
            scrot polkit xfce-polkit rxvt-unicode xdg-user-dirs youtube-dl
            echo "--------------------------"
            echo "install depedency finished"
            echo "--------------------------"
            ;;
        "Install Depedency [ Artix Linux ]")
            sudo pacman -S xorg xorg-server bspwm sxhkd ncmpcpp feh cava mpd mpc \
            fish xsettingsd dunst mpv neofetch neovim thunar rofi viewnior xfce4-power-manager \
            pcmanfm tint2 ranger fontconfig rsync wget curl w3m w3m-img imagemagick pamixer pavucontrol \
            scrot polkit xfce-polkit rxvt-unicode xdg-user-dirs youtube-dl
            echo "--------------------------"
            echo "install depedency finished"
            echo "--------------------------"
            ;;
        "Swicth Shell [ All GNU-Linux ]")
            sudo chsh -s /usr/bin/fish
            echo "--------------------------"
            echo "swicth shell fish finished"
            echo "--------------------------"
            ;;
        "Set Chosser File Use Gtk [ Telegram Desktop ]")
            sudo sed -i -e 's/Exec=telegram-desktop -- %u/Exec=env TDESKTOP_USE_GTK_FILE_DIALOG=1 telegram-desktop -- %u/g' /usr/share/applications/org.telegram.desktop
            sudo sed -i -e 's/Exec=telegram-desktop -- %u/Exec=env TDESKTOP_USE_GTK_FILE_DIALOG=1 telegram-desktop -- %u/g' /usr/share/applications/org.telegram.desktop.desktop
            sudo sed -i -e 's/Exec=telegram-desktop -- %u/Exec=env TDESKTOP_USE_GTK_FILE_DIALOG=1 telegram-desktop -- %u/g' /usr/share/applications/org.telegram.desktop.desktop.desktop
            echo "--------------------------------------------------"
            echo " Ignore if it appears. no such files in directory "
            echo "--------------------------------------------------"
            echo " Set File Chosse Finished "
            echo "--------------------------"
            echo "If not working you can check on [ Desktop Entry ] in the location application of telegram [ /usr/share/applications/ ] you can use command [ ls ] for cheking name of applications missing or not if missing you can edit manualy with add this [ env TDESKTOP_USE_GTK_FILE_DIALOG=1 ] after [ Exec= ]"
            echo "--------------------------"
            ;;
        "Remove Unused File")
            rm -rf ${HOME}/preinstalled && rm -rf ${HOME}/readme.md && rm -rf ${HOME}/LICENCE && rm -rf ${HOME}/preview
            echo "--------------------------"
            echo "remove unused file finished"
            echo "--------------------------"
            ;;
        *) echo "Invalid Selection $REPLY";;
    esac
  break
done
