#!/bin/bash

function main() {
	getRepo >/dev/null 2>&1
	openDir
	insTall

}

function getRepo() {
	find -type d -name "dotbaka" | grep "./" | awk '{ printf $1 }'
}
repo=$(getRepo)

function openDir() {
	cd $repo && git pull # open dir and pulling up
}

function insTall() {
	./install # all file will be update
}

main
