#!/usr/bin/env bash

# init dotbaka
. "${HOME}/.dotbaka"

TEMPS="$(cat /sys/class/power_supply/$BATTERY/capacity | awk '{print $1}')"
echo "<span foreground=\"#16161E\"> </span><span foreground=\"#16161E\">$TEMPS</span>"
