#! /bin/sh

# init dotbaka
. "${HOME}/.dotbaka"

# Make Null Sxhkd -----------------------------------------------------------
pgrep -x sxhkd > /dev/null || sxhkd &
# ----------------------------------------------------------------------------

# Workspace ------------------------------------------------------------------
bspc monitor -d I II III IV V VI VII VIII IX X
# ----------------------------------------------------------------------------

# Window Config --------------------------------------------------------------
bspc config border_width         $W
bspc config window_gap           $G
bspc config top_padding          $T
bspc config bottom_padding       $B
bspc config right_padding        $R
bspc config left_padding         $L
# ----------------------------------------------------------------------------

# Monocle --------------------------------------------------------------------
if [ $MONOCLE = "ON" ]:
then
    bspc config single_monocle       true
fi
# ----------------------------------------------------------------------------

# Visual options -------------------------------------------------------------
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config normal_border_color "$OUTER"
bspc config active_border_color "$ACTIVE"
bspc config focused_border_color "$INNER"
# ----------------------------------------------------------------------------

# Special rules --------------------------------------------------------------
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium follow=on focus=on
bspc rule -a Screenkey manage=off state=floating
bspc rule -a Gpick state=floating follow=on focus=on
bspc rule -a Telegram-Desktop state=floating follow=on focus=on
bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a Org.gnome.Nautilus state=floating follow=on focus=on
bspc rule -a Thunar state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Nm-connection-editor state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a xfce4-power-manager state=floating follow=on focus=on
# ----------------------------------------------------------------------------

# Special Rule For Terminal
if [ $TERMINAL = "floating" ];
then
    bspc rule -a $TERM state=floating follow=on focus=on
fi
if [ $TERMINAL = "full" ];
then
    bspc rule -a $TERM follow=on focus=on
fi
# ----------------------------------------------------------------------------

# Kill Process if running ----------------------------------------------------
pkill sxhkd xfce4-power-manager polybar nautilus
# ----------------------------------------------------------------------------

# Set wall -------------------------------------------------------------------
bash ${HOME}/.fehbg
# ----------------------------------------------------------------------------

# Launch Xsettingsd Daemon ---------------------------------------------------
xsettingsd &
# ----------------------------------------------------------------------------

# Polkit agent ---------------------------------------------------------------
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi
# ----------------------------------------------------------------------------

# Mpd ------------------------------------------------------------------------
mpd ${HOME}/.mpd/mpd.conf &
# ----------------------------------------------------------------------------

# Compositor -----------------------------------------------------------------
if [ $COMPOSITOR = "ON" ];
then
    picom &
fi
# ----------------------------------------------------------------------------

# Keybind --------------------------------------------------------------------
sxhkd &
# ----------------------------------------------------------------------------

# Fix Java App ---------------------------------------------------------------
if [ $FIX_JAVA_APP = "ON" ];
then
    wmname LG3D &
fi
# ----------------------------------------------------------------------------

# Pwr Manager ----------------------------------------------------------------
if [ $XFCE4_POWER = "ON" ];
then
    xfce4-power-manager &
fi
# ----------------------------------------------------------------------------

# Brightness Set -------------------------------------------------------------
if [ $BACKLIGHT_SET = "ON" ];
then
    xbacklight -set $VALUE &
fi
# ----------------------------------------------------------------------------

# Fix Cursor "X" -------------------------------------------------------------
xsetroot -cursor_name left_ptr &
# ----------------------------------------------------------------------------

# BAR ------------------------------------------------------------------------
if [ $BAR = "polybar" ];
then
    bash ~/.config/polybar/launch &
fi
if [ $BAR = "tint2" ];
then
    bash ~/.config/tint2/citrus/launch &
fi
# ----------------------------------------------------------------------------

# Pulseaudio In Background ---------------------------------------------------
pulseaudio --daemonize=no --exit-idle-time=-1 &
# ----------------------------------------------------------------------------
