#!/usr/bin/env sh

# ENV
CONFIG_DIR="$XDG_CONFIG_HOME/tint2/rich"

# with widget
widget() {
  if [[ "$(pidof tint2)" != "" ]]; then
    pkill tint2
  fi

  tint2 -c "$CONFIG_DIR/clockrc" &> /dev/null &
  tint2 -c "$CONFIG_DIR/tasksrc" &> /dev/null &
  tint2 -c "$CONFIG_DIR/menusrc" &> /dev/null &
  tint2 -c "$CONFIG_DIR/confsrc" &> /dev/null &
  tint2 -c "$CONFIG_DIR/networc" &> /dev/null &
}

# no widget
no_widget() {
  if [[ "$(pidof tint2)" != "" ]]; then
    pkill tint2
  fi

  tint2 -c "$CONFIG_DIR/tasksrc" &> /dev/null &
  tint2 -c "$CONFIG_DIR/menusrc" &> /dev/null &
  tint2 -c "$CONFIG_DIR/networc" &> /dev/null &
}

case ${1} in
    --widget)
      widget
      ;;
    --nowidget)
      no_widget
      ;;
esac

exit ${?}
