#!/bin/bash

case "$1" in
  --i)
    brightness=$(xbacklight -inc 1 | cut -f 1 -d '.')
    dunstify "盛 Brigthness Up:" -h int:value:$brightness -t 1000 -r 1
    ;;
  --d)
    brightness=$(xbacklight -dec 1 | cut -f 1 -d '.')
    dunstify "滛 Brigthness Down:" -h int:value:$brightness -t 1000 -r 1
    ;;
esac
