#!/bin/sh/env sh

# Rofi Command
rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/misc.rasi -show"

# Themes
compositor_1=""
compositor_2="ﬆ"

# Variable passed to rofi
options="$compositor_1\n$compositor_2"

chosen="$(echo -e "$options" | $rofi_command -p "compositor / picom" -show -dmenu -sync -selected-row 0)"
case $chosen in
    $compositor_1)
        sed -i -e 's/corner-radius = 0/corner-radius = 8/g' ${HOME}/.config/picom/picom.conf
        ;;
    $compositor_2)
        sed -i -e 's/corner-radius = 8/corner-radius = 0/g' ${HOME}/.config/picom/picom.conf
        ;;
esac
