#!/usr/bin/env bash

rofi_command="rofi -lines 5 -theme $HOME/.config/rofi/menu/config.rasi"

# option
theme=" : Theme"
network=" : Network"
model=" : Compositor"
power=" : Powermenu"
screenshot=" : Screenshots"

# Variable passed to rofi
options="$theme\n$network\n$model\n$power\n$screenshot"

# Spawn menu
chosen="$(echo -e "$options" | $rofi_command -p "Menu" -dmenu)"
case $chosen in
    $network)
        bash ${HOME}/.scripts/network
        ;;
    $theme)
        bash ${HOME}/.scripts/set-theme
        ;;
    $model)
        bash ${HOME}/.scripts/set-compositor
        ;;
    $power)
        rofi -show p -modi p:${HOME}/.scripts/powermenu \
             -theme ${HOME}/.config/rofi/menu/config.rasi \
             -font "Iosevka Nerd Font Complete 10" \
             -width 20 \
             -lines 2
        ;;
    $screenshot)
	rofi -show p -modi p:${HOME}/.scripts/rofiss \
             -theme ${HOME}/.config/rofi/menu/config.rasi \
             -font "Iosevka Nerd Font Complete 10" \
             -width 20 \
             -lines 3
	;;
esac
