#!/bin/bash

rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/powermenu.rasi -show"

symbols=("" "" "鈴" "")
icons=("${HOME}/.icons/Tela-grey/24/actions/application-exit.svg" \
       "${HOME}/.icons/Tela-grey/scalable/apps/system-restart.svg" \
       "${HOME}/.icons/Tela-grey/scalable/apps/system-suspend.svg" \
       "${HOME}/.icons/Tela-grey/scalable/apps/system-log-out.svg")
options=("logout the system" "reboot the system" "suspend the system" "poweroff the system")
actions=("exit" "reboot" "suspend" "poweroff")

menu=""
for s in "${symbols[@]}"; do
    menu="$menu$s\n"
done

function power_action {
    dunstify -i "${icons[$1]}" "$2" -t 1000 -r 1
    sleep 0.5
    loginctl ${actions[$1]}
}

chosen="$(echo -e "$menu" | $rofi_command -p "powermenu" -dmenu -selected-row 0)"
if [[ -n "$chosen" ]]; then
    if ! power_action "$chosen" "${options[$chosen]}"; then
        dunstify "Error: failed to ${options[$chosen]}" -t 1000 -u critical
    fi
fi
