#!/bin/sh/env sh

# Rofi Command
rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/powermenu.rasi -show"

# Border
s1=""
s2=""
s3="鈴"
s4=""

# Variable passed to rofi
options="$s1\n$s2\n$s3\n$s4"

chosen="$(echo -e "$options" | $rofi_command -p "powermenu" -dmenu -sync -selected-row 0)"
case $chosen in
    $s1)
        dunstify -i "~/.icons/Tela-grey/24/actions/application-exit.svg" "logout the system" -t 1000 -r 1
        sleep 0.5
        loginctl exit
        ;;
    $s2)
        dunstify -i "~/.icons/Tela-grey/scalable/apps/system-restart.svg" "reboot the system" -t 1000 -r 1
        sleep 0.5
        loginctl reboot
        ;;
    $s3)
        dunstify -i "~/.icons/Tela-grey/scalable/apps/system-suspend.svg" "suspend the system" -t 1000 -r 1
        sleep 0.5
        loginctl suspend
        ;;
    $s4)
        dunstify -i "~/.icons/Tela-grey/scalable/apps/system-log-out.svg" "poweroff the system" -t 1000 -r 1
        sleep 0.5
        loginctl poweroff
        ;;
esac
