#!/bin/bash/env bash

# Rofi Command
rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/powermenu.rasi -show"

# Border
s1=""
s2=""
s3="鈴"
s4=""

# Variable passed to rofi
options="$s1\n$s2\n$s3\n$s4"

chosen="$(echo -e "$options" | $rofi_command -p "powermenu" -dmenu -sync -selected-row 0)"
case $chosen in
    $s1)
        dunstify "logout the system"
        sleep 1
        loginctl exit
        ;;
    $s2)
        dunstify "reboot the system"
        sleep 1
        loginctl reboot
        ;;
    $s3)
        dunstify "suspend the system"
        sleep 1
        loginctl suspend
        ;;
    $s4)
        dunstify "poweroff the system"
        sleep 1
        loginctl poweroff
        ;;
esac
