#!/bin/bash

# directory
DIR="$HOME/Videos"

# get reso
function Greso() {
        xdpyinfo | grep dimensions | awk '{print $2}'
}
reso=$(Greso)

# file video
NAME="$DIR/video-$(date '+%y%m%d-%H%M-%S').mp4"

# notify send
notify-send "Start Recording" "In Time: $(date '+%H:%M:%S')"

ffmpeg -y -f x11grab -framerate 30 -s $reso \
       -i :0.0 -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 \
       -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 $NAME &

echo $! >/tmp/record
