#!/bin/bash/env bash

# Rofi Command
rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/screenshot.rasi -show"

# Border
s1="screenshot"
s2="screenshot-3s"
s3="screenshot-5s"
s4="screenshot-area"

# Variable passed to screenshots
SAVE_DIR="${HOME}/Pictures/Screenshots"

# Create directory if needed
if [ ! -d "$SAVE_DIR" ]; then
    mkdir -p "$SAVE_DIR"
fi

# Variable passed to rofi
options="$s1\n$s2\n$s3\n$s4"

chosen="$(echo -e "$options" | $rofi_command -p "select one type of screenshots" -dmenu -sync -selected-row 0)"
case $chosen in
    $s1)
        scrot '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        dunstify -i "SCROT" -u low "" "<span size='small'><u>Pictures/Screenshots</u></span>\nChissu! Take Screenshot"
        ;;
    $s2)
        scrot -d 3 '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        dunstify -i "SCROT" -u low "" "<span size='small'><u>Pictures/Screenshots</u></span>\nChissu! Take Screenshot"
        ;;
    $s3)
        scrot -d 5 '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        dunstify -i "SCROT" -u low "" "<span size='small'><u>Pictures/Screenshots</u></span>\nChissu! Take Screenshot"
        ;;
    $s4)
        scrot --line style=dash,width=2,color="white" --select '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        dunstify -i "SCROT" -u low "" "<span size='small'><u>Pictures/Screenshots</u></span>\nChissu! Take Screenshot"
        ;;
esac
