#!/bin/bash

rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/screenshot.rasi -show"
options=( "" "3" "5" "" )

# Create directory if needed
SAVE_DIR="${HOME}/Pictures/Screenshots"
[[ -d "$SAVE_DIR" ]] || mkdir -p "$SAVE_DIR"

# Take screenshot based on user selection
chosen=$(printf '%s\n' "${options[@]}" | $rofi_command -p "screenshots" -dmenu -sync -selected-row 0)
case $chosen in
    "")
        sleep 0.5
        scrot '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        ;;
    "3")
        scrot -d 3 '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        ;;
    "5")
        scrot -d 5 '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        ;;
    "")
        scrot --line style=dash,width=2,color="white" --select '%Y-%m-%d-%T-screenshot.png' -e 'mv $f ~/Pictures/Screenshots'
        ;;
esac

# Add border and round corners
if [[ -f "$SAVE_DIR/%Y-%m-%d-%T-screenshot.png" ]]; then
    convert "$SAVE_DIR/%Y-%m-%d-%T-screenshot.png" \
        -bordercolor black -border 15 \
        -alpha set -background none \
        -vignette 0x4 -blur 0x5 \
        -alpha shape "$SAVE_DIR/%Y-%m-%d-%T-screenshot.png"
    dunstify -i "SCROT" -u low "" "<span size='small'><u>Pictures/Screenshots</u></span>\nChissu! Take Screenshot"
fi
