#!/bin/bash/env

# Rofi Command
rofi_command="rofi -lines 2 -theme ${HOME}/.config/rofi/menu/config.rasi"

# Themes
theme_0=" Twilight"
theme_1=" Baka"

# Variable passed to rofi
options="$theme_0\n$theme_1"

chosen="$(echo -e "$options" | $rofi_command -p "Switch Themes" -show -dmenu -sync -selected-row 0)"
case $chosen in
    $theme_0)y
	# Kill Process if running ----------------------
        killall alacritty rofi sxhkd dunst xfce4-power-manager tint2
        # ----------------------------------------------
        sed -i -e 's/Baka/Twilight/g' ${HOME}/.xsettingsd
	    sed -i -e 's/#7E9DBC/#E48D7B/g' ${HOME}/.scripts/selfdraw.sh
        sed -i -e 's/baka/twilight/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/baka/twilight/g' ${HOME}/.config/rofi/menu/config.rasi
        sed -i -e 's/#16161E/#141634/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/oreo_white_cursors/oreo_red_cursors/g' ${HOME}/.xsettingsd
        sed -i -e 's/background = "##16161E"/background = "#141634"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#141634"/foreground = "#F9F9F9"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/bakarc/twilightrc/g' ${HOME}/.config/bspwm/bspwmrc
        sed -i -e 's/hentai.png/rewhet.png/g' ${HOME}/.fehbg
        # Kill terminal --------------------------------
        killall $USR1 alacritty
        # ----------------------------------------------
        bspc wm -r
        ;;
    $theme_1)
	# Kill Process if running ----------------------
        killall alacritty rofi sxhkd dunst xfce4-power-manager tint2
        # ----------------------------------------------
        sed -i -e 's/Twilight/Baka/g' ${HOME}/.xsettingsd
	    sed -i -e 's/#E48D7B/#7E9DBC/g' ${HOME}/.scripts/selfdraw.sh
        sed -i -e 's/twilight/baka/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/twilight/baka/g' ${HOME}/.config/rofi/menu/config.rasi
        sed -i -e 's/#141634/#16161E/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/oreo_red_cursors/oreo_white_cursors/g' ${HOME}/.xsettingsd
        sed -i -e 's/background = "#141634"/background = "##16161E"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#F9F9F9"/foreground = "#141634"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/twilightrc/bakarc/g' ${HOME}/.config/bspwm/bspwmrc
        sed -i -e 's/rewhet.png/hentai.png/g' ${HOME}/.fehbg
        # Kill terminal --------------------------------
        killall $USR1 alacritty
        # ----------------------------------------------
        bspc wm -r
        ;;
esac
