#!/bin/bash/env bash

# Rofi Command
rofi_command="rofi -lines 2 -theme ${HOME}/.config/rofi/menu/config.rasi"

# Border
border_1="絛 Make Border"
border_2="窱 Remove Border"

# Variable passed to rofi
options="$border_1\n$border_2"

chosen="$(echo -e "$options" | $rofi_command -p "Switch Type Border" -show -dmenu -sync -selected-row 0)"
case $chosen in
    $border_1)
        sed -i -e 's/bspc config border_width         0/bspc config border_width         5/g' ${HOME}/.config/bspwm/bspwmrc
        bspc wm -r
        ;;
    $border_2)
        sed -i -e 's/bspc config border_width         5/bspc config border_width         0/g' ${HOME}/.config/bspwm/bspwmrc
        bspc wm -r
        ;;
esac

