#!/bin/bash/env

# Rofi Command
rofi_command="rofi -theme ${HOME}/.config/rofi/menu/config.rasi"

# Themes
theme_0=" Twilight"
theme_1=" Baka"

# Variable passed to rofi
options="$theme_0\n$theme_1"

chosen="$(echo -e "$options" | $rofi_command -p "Switch Themes" -show -dmenu -sync -selected-row 0)"
case $chosen in
    $theme_0)
	# Kill Process if running ----------------------
        killall alacritty rofi sxhkd dunst xfce4-power-manager tint2
        # ----------------------------------------------
        sed -i -e 's/Baka/Twilight/g' ${HOME}/.xsettingsd
        sed -i -e 's/Tela-grey/Tela-red/g' ${HOME}/.xsettingsd
	sed -i -e 's/#7E9DBC/#141634/g' ${HOME}/.scripts/selfdraw.sh
        sed -i -e 's/baka/twilight/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/baka/twilight/g' ${HOME}/.config/rofi/menu/config.rasi
        sed -i -e 's/#2e3440/#141634/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/oreo_white_cursors/oreo_red_cursors/g' ${HOME}/.xsettingsd
        sed -i -e 's/background = "#2E3440"/background = "#141634"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#141634"/foreground = "#F9F9F9"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/gtk-theme-name=Baka/gtk-theme-name=Twilight/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/gtk-icon-theme-name=Assistance/gtk-theme-name=Lolipop/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/bakarc/twilightrc/g' ${HOME}/.config/bspwm/bspwmrc
        sed -i -e 's/dusk.jpg/light.png/g' ${HOME}/.fehbg
        # Kill terminal --------------------------------
        killall $USR1 alacritty
        # ----------------------------------------------
        bspc wm -r
        ;;
    $theme_1)
	# Kill Process if running ----------------------
        killall alacritty rofi sxhkd dunst xfce4-power-manager tint2
        # ----------------------------------------------
        sed -i -e 's/Twilight/Baka/g' ${HOME}/.xsettingsd
        sed -i -e 's/Tela-red/Tela-grey/g' ${HOME}/.xsettingsd
	sed -i -e 's/#141634/#7E9DBC/g' ${HOME}/.scripts/selfdraw.sh
        sed -i -e 's/twilight/baka/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/twilight/baka/g' ${HOME}/.config/rofi/menu/config.rasi
        sed -i -e 's/#141634/#2e3440/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/oreo_red_cursors/oreo_white_cursors/g' ${HOME}/.xsettingsd
        sed -i -e 's/background = "#141634"/background = "#2E3440"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#F9F9F9"/foreground = "#141634"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/gtk-theme-name=Twilight/gtk-theme-name=Baka/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/gtk-icon-theme-name=Lolipop/gtk-theme-name=Assistance/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/twilightrc/bakarc/g' ${HOME}/.config/bspwm/bspwmrc
        sed -i -e 's/light.png/dusk.jpg/g' ${HOME}/.fehbg
        # Kill terminal --------------------------------
        killall $USR1 alacritty
        # ----------------------------------------------
        bspc wm -r
        ;;
esac
