#!/bin/sh/env sh

# Rofi Command
rofi_command="rofi -lines 2 -theme ${HOME}/.config/rofi/misc/misc.rasi"

# Themes
theme_0="richblack"
theme_1="citrus"

# Variable passed to rofi
options="$theme_0\n$theme_1"

chosen="$(echo -e "$options" | $rofi_command -p "themes" -show -dmenu -sync -selected-row 0)"
case $chosen in
    $theme_0)
	    # Kill Process if running ----------------------
        bash ~/.scripts/killapp
        # ----------------------------------------------
        sed -i -e 's/timberwolf/richblack/g' ${HOME}/.xsettingsd
        sed -i -e 's/citrus/rich/g' ${HOME}/.config/bspwm/bspwmrc
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/clean.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/timberwolf/richblack/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/misc.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/ytdl.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/search.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/network.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/powermenu.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/screenshot.rasi
        sed -i -e 's/background = "#724439"/background = "#16161E"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#16161E"/foreground = "#724439"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/light/dark/g' ${HOME}/.config/polybar/config.ini
        sed -i -e 's/citrus.png/blue-archive.png/g' ${HOME}/.fehbg
        # Restart wm without exit ----------------------
        bspc wm -r
        # Kill Alacritty Only --------------------------
        pkill alacritty
        # Tint2 fix always on top ----------------------
        bash ~/.scripts/alwaysinbellow
        # ----------------------------------------------
        ;;
    $theme_1)
        # Kill Process if running ----------------------
        pkill alacritty sxhkd dunst polybar tint2
        # ----------------------------------------------
        sed -i -e 's/timberwolf/richblack/g' ${HOME}/.xsettingsd
        sed -i -e 's/rich/citrus/g' ${HOME}/.config/bspwm/bspwmrc
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/clean.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/richblack/timberwolf/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/misc.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/ytdl.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/search.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/network.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/powermenu.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/screenshot.rasi
        sed -i -e 's/background = "#16161E"/background = "#724439"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#724439"/foreground = "#16161E"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/dark/light/g' ${HOME}/.config/polybar/config.ini
        sed -i -e 's/blue-archive.png/citrus.png/g' ${HOME}/.fehbg
        # Restart wm without exit ----------------------
        bspc wm -r
        # Kill Alacritty Only --------------------------
        pkill alacritty
        # Tint2 fix always on top ----------------------
        bash ~/.scripts/alwaysinbellow
        # ----------------------------------------------
        ;;
esac
