#!/bin/bash

rofi_command="rofi -lines 2 -theme ${HOME}/.config/rofi/misc/misc.rasi"

# Themes
themes=("livery" "citrus")
theme_colors=(
  "timberwolf:richblack citrus:rich light:dark"
  "timberwolf:richblack rich:citrus dark:light"
)
theme_files=(
  "${HOME}/.xsettingsd ${HOME}/.config/bspwm/bspwmrc \
   ${HOME}/.config/gtk-3.0/settings.ini \
   ${HOME}/.config/alacritty/alacritty.yml \
   ${HOME}/.config/polybar/config.ini \
   ${HOME}/.fehbg"
  "${HOME}/.config/rofi/clean.rasi ${HOME}/.config/rofi/config.rasi \
   ${HOME}/.config/rofi/misc/misc.rasi ${HOME}/.config/rofi/misc/ytdl.rasi \
   ${HOME}/.config/rofi/misc/search.rasi ${HOME}/.config/rofi/misc/network.rasi \
   ${HOME}/.config/rofi/misc/powermenu.rasi ${HOME}/.config/rofi/misc/screenshot.rasi \
   ${HOME}/.config/dunst/dunstrc"
)

# Get chosen theme
options=$(printf '%s\n' "${themes[@]}")
chosen="$(echo -e "$options" | $rofi_command -p "themes" -show -dmenu -sync -selected-row 0)"

# Apply chosen theme
theme_index=$(echo "${themes[@]}" | grep -o "$chosen" | wc -w)
if [[ $theme_index -eq 0 ]]; then
  exit
fi
theme_index=$((theme_index - 1))
theme_color=${theme_colors[$theme_index]}
theme_files=${theme_files[$theme_index]}

# Kill processes
killall alacritty sxhkd dunst polybar tint2

# Update files
IFS=' ' read -ra files <<< "$theme_files"
IFS=' ' read -ra colors <<< "$theme_color"
for (( i=0; i<${#files[@]}; i++ )); do
  sed -i "s/${colors[i]}/g" "${files[i]}"
done

# Restart wm without exit
bspc wm -r

# Tint2 fix always on top
killall tint2
sleep 0.1
tint2 &

# Exit
exit 0
