#!/bin/bash/env

# Rofi Command
rofi_command="rofi -lines 2 -theme ${HOME}/.config/rofi/misc/misc.rasi"

# Themes
theme_0="raisinblack"
theme_1="timberwolf"

# Variable passed to rofi
options="$theme_0\n$theme_1"

chosen="$(echo -e "$options" | $rofi_command -p "themes" -show -dmenu -sync -selected-row 0)"
case $chosen in
    $theme_0)
	    # Kill Process if running ----------------------
        pkill alacritty sxhkd dunst polybar
        # ----------------------------------------------
        sed -i -e 's/black,white/black,cyan/g' ${HOME}/.nanorc
        sed -i -e 's/Timberwolf/Raisinblack/g' ${HOME}/.xsettingsd
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/clean.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/Timberwolf/Raisinblack/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/misc.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/search.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/network.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/powermenu.rasi
        sed -i -e 's/light/dark/g' ${HOME}/.config/rofi/misc/screenshot.rasi
        sed -i -e 's/background = "#DFD6CF"/background = "#16161E"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#16161E"/foreground = "#DFD6CF"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/light/dark/g' ${HOME}/.config/polybar/config.ini
        sed -i -e 's/office-lady.png/blue-archive.png/g' ${HOME}/.fehbg
        bspc wm -r
        ;;
    $theme_1)
        # Kill Process if running ----------------------
        pkill alacritty sxhkd dunst polybar
        # ----------------------------------------------
        sed -i -e 's/black,cyan/black,white/g' ${HOME}/.nanorc
        sed -i -e 's/Timberwolf/Raisinblack/g' ${HOME}/.xsettingsd
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/clean.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/config.rasi
        sed -i -e 's/Raisinblack/Timberwolf/g' ${HOME}/.config/gtk-3.0/settings.ini
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/misc.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/search.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/network.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/alacritty/alacritty.yml
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/powermenu.rasi
        sed -i -e 's/dark/light/g' ${HOME}/.config/rofi/misc/screenshot.rasi
        sed -i -e 's/background = "#16161E"/background = "#DFD6CF"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/foreground = "#DFD6CF"/foreground = "#16161E"/g' ${HOME}/.config/dunst/dunstrc
        sed -i -e 's/dark/light/g' ${HOME}/.config/polybar/config.ini
        sed -i -e 's/blue-archive.png/office-lady.png/g' ${HOME}/.fehbg
        bspc wm -r
        ;;
esac
