#!/usr/bin/env sh

type -p pamixer &>/dev/null || dunstify -u low -r 15 'Install pamixer!'

VOLUME="$(pamixer --get-volume)"

notify() {
  if [ "$VOLUME" -lt 0 ];then
    ICON="ﱝ"
  elif [ "$VOLUME" -lt 30 ];then
    ICON=""
  elif [ "$VOLUME" -lt 70 ];then
    ICON="墳"
  else 
    ICON=""
  fi
  dunstify "$ICON Volume:" -h int:value:$VOLUME -t 1000 -r 1
}

case ${1} in
    --i)
        pamixer --increase 5
      ;; 
    --d)
        pamixer --decrease 5
      ;;
esac
      
notify

exit ${?}
