#!/bin/bash

command -v pamixer >/dev/null 2>&1 || { dunstify -u low -r 15 'Install pamixer!'; exit 1; }

VOLUME="$(pamixer --get-volume)"

notify() {
  case $VOLUME in
    [0-9]|[1-2][0-9])
      ICON="ﱝ"
      ;;
    [3-6][0-9])
      ICON=""
      ;;
    *)
      ICON=""
      ;;
  esac
  dunstify "$ICON Volume:" -h int:value:$VOLUME -t 1000 -r 1
}

case ${1} in
    --i)
        pamixer --increase 5
      ;; 
    --d)
        pamixer --decrease 5
      ;;
esac
      
notify

exit $?
