#!/usr/bin/env bash

MENU="$HOME/.config/rofi/misc/misc.rasi"
MUSIC="$HOME/Music"

# Rofi prompt
rofi_prompt="Download Mp3  ="

# rofi
main() {
    # Get choice from rofi
    choice=$( rofi -lines 1 -dmenu -theme "$MENU" -i -fuzzy -p "$rofi_prompt" )

  # If user has not picked anything, exit
  if [[ -z "${choice// }" ]]; then
      exit 1
  fi

  # Get URL
  linktoplay="$(grep -m 1 "$choice" | cut -d '@' -f 2)"

  # If the choice does not exist, try searching for it
  if [ ${#linktoplay} -eq "0" ]; then
    yid=$(youtube-dl -q --get-title --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0 ytsearch:"$choice")
    notify-send -i "Move" -u low "" "<span size='small'><u>$HOME/Music</u></span>\n$yid"
  fi

  # Create directory if needed
  if [ ! -d "$MUSIC" ]; then
      mkdir -p "$MUSIC"
  fi
}

getname() {
    ls *mp3 | awk '{print 1}'
}

movefile() {
    mv $getname ${HOME}/Music
}

main &
getname &
movefile &

exit 0
