#!/bin/bash

readonly MENU="$HOME/.config/rofi/misc/ytdl.rasi"
readonly MUSIC="$HOME/Music"
readonly ICON="$HOME/.icons/Tela-grey/scalable/apps/music_icon-24.svg"

# Rofi prompt
readonly rofi_prompt="Download Mp3  ="

# Create directory if needed
if [ ! -d "$MUSIC" ]; then
  mkdir -p "$MUSIC"
fi

while true; do
  # Get choice from rofi
  read -r choice < <(rofi -lines 1 -dmenu -theme "$MENU" -i -fuzzy -p "$rofi_prompt")

  # If user has not picked anything, exit
  if [[ -z "${choice// }" ]]; then
    exit 1
  fi

  # Get video title and download mp3
  yid=$(youtube-dl -q --get-title --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0 --output "$MUSIC/%(title)s.%(ext)s" --match-title "$choice")
  printf '<span size="small"><u>%s</u></span>\n%s\n' "$MUSIC" "$yid" | notify-send -i "$ICON" -u low ""

  # Ask if user wants to download another mp3
  read -p "Download another mp3? [y/N]: " answer
  case "$answer" in
    [yY]) continue;;
    *) break;;
  esac
done
