#!/usr/bin/env bash

# Configuration
menu="$HOME/.config/rofi/misc/ytdl.rasi"
mpv_args="-shuffle --yes-playlist --force-window=immediate"
rofi_prompt="YouTube   ="
icon_path="$HOME/.icons/Tela-grey/scalable/apps/youtube.svg"

# Main function
main() {
    # Get choice from rofi
    choice=$(rofi -lines 1 -dmenu -theme "$menu" -i -fuzzy -p "$rofi_prompt")

    # If user has not picked anything, exit
    if [[ -z "${choice// }" ]]; then
        exit 1
    fi

    # Get URL
    url=$(grep -m 1 "@$choice" "$HOME/.config/rofi/misc/ytdl-links" | cut -d '@' -f 2)

    # If the choice does not exist, try searching for it
    if [[ -z "$url" ]]; then
        yid=$(youtube-dl "ytsearch:$choice" -s --get-id)
        url="https://www.youtube.com/watch?v=$yid"
    fi

    # Send notification
    notify-send -i "$icon_path" "Opening YouTube Video:" "$url"

    # Spawn mpv
    mpv $mpv_args "$url"
}

# Run main function in background and exit
main &
exit 0
